Add wrapper for `ua::RelativePathElement`
HMIProject/open62541 pull request #130
Opened 2024-07-12 13:32 UTC by sgoll

## Description

This adds the wrapper type `ua::RelativePathElement` with safe constructor methods.

2024-07-15 13:09 UTC, uklotzde approved these changes

2024-07-15 14:00 UTC, LeanderGlanda requested changes
Just found out about how this feature is works. See the above message for info on my requested changes.

2024-07-16 06:13 UTC, LeanderGlanda commented
So I just found out that `UA_BrowsePath_new` is just uses `calloc` in the background and `UA_BrowsePath_init` uses ´memset`. So I don't know any reason using `UA_BrowsePath_new` over `UA_BrowsePath_init`.
Removing the `UA_BrowsePath_new` is fine then.

I also didn't get that there was an default init() function present. So you are right.

The changes look good to me.

2024-07-16 06:14 UTC, LeanderGlanda approved these changes

2024-07-16 11:21 UTC, merged